### ISSUE TITLE
Add libsignal-metadata-dotnet nuget package to signal-csharp organization

### ISSUE THREAD

**Issue by golf1052** [signal-csharp/libsignal-metadata-dotnet#1]
@Trolldemorted 

I created an organization on nuget.org called [signal-csharp](https://www.nuget.org/profiles/signal-csharp) to hold ownership of our packages. When you get a chance could you add [libsignal-metadata-dotnet](https://www.nuget.org/packages/libsignal-metadata-dotnet/) to that organization so I can push package updates to nuget? I already added you as an administrator on the org, you just need to accept the request.

**Comment by Trolldemorted** [comment]
Done!
