### ISSUE TITLE
Why are we using proto3 for proto files?

### ISSUE THREAD

**Issue by golf1052** [signal-csharp/libsignal-metadata-dotnet#2]
[libsignal-metadata-java](https://github.com/signalapp/libsignal-metadata-java) uses proto2 for its protobuf files, why are we using proto3 here?

@Trolldemorted

**Comment by Trolldemorted** [comment]
I think because there were no official protobuf2 compilers for c# around, and protobuf3 is backwards compatible to protobuf2

**Comment by golf1052** [comment]
I migrated to proto2 in this commit https://github.com/signal-csharp/libsignal-metadata-dotnet/commit/dd6e4626f1b73f0d76c5b650a217864ffea7a412

The protoc compiler provided by Google works with C# for proto2 and proto3.
